create table if not exists KEY_TYPE(
    KEY_TYPE_ID     SMALLINT    NOT NULL,
    DESCRIPTION     VARCHAR(9)  NOT NULL,
    CREATED_AT      TIMESTAMP   NOT NULL,
    UPDATED_AT      TIMESTAMP       NULL,
CONSTRAINT PK_KEY_TYPE PRIMARY KEY (KEY_TYPE_ID)
);

create table if not exists CLIENT(
    CLIENT_ID       SERIAL      NOT NULL,
    FIRST_NAME      VARCHAR(30) NOT NULL,
    LAST_NAME       VARCHAR(45)     NULL,
    PERSON_TYPE     VARCHAR(1)  NOT NULL,
    CREATED_AT      TIMESTAMP   NOT NULL,
    UPDATED_AT      TIMESTAMP       NULL,
CONSTRAINT PK_CLIENT PRIMARY KEY (CLIENT_ID)
);

create table if not exists ACCOUNT(
    ACCOUNT_ID      SERIAL      NOT NULL,
    BRANCH_NUMBER   INTEGER     NOT NULL,
    ACCOUNT_NUMBER  INTEGER     NOT NULL,
    ACCOUNT_TYPE    VARCHAR(10) NOT NULL,
    CLIENT_ID       SMALLINT    NOT NULL,
    CREATED_AT      TIMESTAMP   NOT NULL,
    UPDATED_AT      TIMESTAMP       NULL,
CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
CONSTRAINT FK_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
);

create table if not exists PIX_KEY(
    PIX_KEY_ID      VARCHAR(36) NOT NULL,
    VALUE           VARCHAR(77) NOT NULL,
    KEY_TYPE_ID     SMALLINT    NOT NULL,
    ACCOUNT_ID      SMALLINT    NOT NULL,
    CREATED_AT      TIMESTAMP   NOT NULL,
    UPDATED_AT      TIMESTAMP       NULL,
CONSTRAINT PK_PIX_KEY PRIMARY KEY (PIX_KEY_ID),
CONSTRAINT FK_KEY_TYPE FOREIGN KEY (KEY_TYPE_ID) REFERENCES KEY_TYPE(KEY_TYPE_ID),
CONSTRAINT FK_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);