INSERT INTO KEY_TYPE (KEY_TYPE_ID, DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES (1, 'CELULAR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (KEY_TYPE_ID) DO NOTHING;

INSERT INTO KEY_TYPE (KEY_TYPE_ID, DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES (2, 'EMAIL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (KEY_TYPE_ID) DO NOTHING;

INSERT INTO KEY_TYPE (KEY_TYPE_ID, DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES (3, 'CPF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (KEY_TYPE_ID) DO NOTHING;

INSERT INTO KEY_TYPE (KEY_TYPE_ID, DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES (4, 'CNPJ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (KEY_TYPE_ID) DO NOTHING;

INSERT INTO KEY_TYPE (KEY_TYPE_ID, DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES (5, 'ALEATORIO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (KEY_TYPE_ID) DO NOTHING;